= Installing AsciiDoc on macOS and Windows

AsciiDoc is a lightweight markup language that can be used to create documents in a plain text format. It is a popular choice for creating technical documentation, books, and articles. This guide will show you how to install AsciiDoc on both macOS and Windows.

== Prerequisites

Before you can install AsciiDoc, you will need to have the following software installed on your machine:

* On macOS: [Homebrew](https://brew.sh/) - a package manager for macOS
* On Windows: [Ruby](https://www.ruby-lang.org/en/downloads/) - a programming language that is required to run AsciiDoc, [RubyGems](https://rubygems.org/) - a package manager for Ruby

== Installing AsciiDoc

=== On macOS

To install AsciiDoc on macOS, you will need to use the Homebrew package manager.

1. Open a terminal window.
2. Install AsciiDoc by running the following command:

[source,bash]
----
brew install asciidoc
----

3. Verify the installation by running the following command:

[source,bash]
----
asciidoc --version
----

You should see the version of AsciiDoc that you just installed.

=== On Windows

To install AsciiDoc on Windows, you will need to use the RubyGems package manager.

1. Open a command prompt window.
2. Install AsciiDoc by running the following command:

[source,bash]
----
gem install asciidoctor
----

3. Verify the installation by running the following command:

[source,bash]
----
asciidoctor --version
----

You should see the version of AsciiDoc that you just installed.

== Using AsciiDoc

To create an AsciiDoc document, you will need to create a plain text file with the `.asciidoc` file extension. You can then use the `asciidoctor` command on Windows or `asciidoc` command on macOS to convert the file to various formats such as HTML, PDF, and EPUB.

For example, to convert an AsciiDoc file named `example.asciidoc` to HTML, you can use the following command:

[source,bash]
----
asciidoctor example.asciidoc  # for windows
asciidoc -b html5 example.asciidoc # for mac
----

This will create an HTML file named `example.html` in the same directory as the AsciiDoc file.

